# Generated by Django 5.0.1 on 2024-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_clean_method_validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.CharField(max_length=10, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sal',
            field=models.FloatField(verbose_name='Salary'),
        ),
    ]
