# Generated by Django 5.0.1 on 2024-01-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_clean_method_validator', '0002_alter_employee_e_id_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='c_password',
            field=models.CharField(default='same pass here..', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='password here...', max_length=20),
        ),
    ]
